import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import theme from "../theme";
import "./globals.css";
import BottomNavBar from "@/app/components/BottomNavBar";
import MainHeader from "./components/MainHeader";
import { Query } from "@tanstack/react-query";
import QueryClientProvider from "./QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <QueryClientProvider>
          <InitColorSchemeScript attribute="class" />
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <header>
                <MainHeader />
              </header>
              <main>{children}</main>
              <footer className="h-12">
                <BottomNavBar />
              </footer>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
